### ISSUE TITLE
How can I use the implicit login registration page from jhipster ( spring boot,)  instead of keycloak login window?

### ISSUE THREAD

**Issue by dkarthi1973** [dsb-norge/vue-keycloak-js#50] opened 2020-08-25 11:46 UTC
I have tried to register new user from Jhipster (Oauth2, keycloak)  but getting authorization error.( based on bearer token ). If any reference, please let us know.

**Comment by nlien** [comment] 2020-09-03 11:33
Hi there. How is this an issue concerning this plugin?
I am not aware of any JHipster scaffolding that uses this plugin, and if so, it would be hard to follow up your issue without any indications of what is wrong here. No error messages, stacktraces, reproducing steps... 

Despite being actively involved in the continuation of this plugin, I'm inclined to propose closing this issue.

**Comment by anderius** [comment] 2020-09-11 09:53
I am closing this issue due to lack of feedback.

**Closed by anderius** 2020-09-11 09:53 UTC
